### ISSUE TITLE
Import characters into Initiative Tracker, Party Skill Checker and Party Manager

### ISSUE THREAD

**Issue by samcorcoran** [tsiemens/pathfinder-toolkit#17]
Characters created in the 'Characters' view are currently inaccessible in all other views except for the 'Pointbuy Calculator' view.

The 'Pointbuy Calculator' view includes an import button (top right of screen, next to add new character button) which allows user to select a pre-made character to use (known in the code as 'mi_export_to_existing').

Including this same button and functionality in the Initiative Tracker, Party Skill Checker and Party Manager views would allow a user to avoid remaking character templates for their party if they wish to roll initiative for a bunch of pre-made characters.

Populating, for example, the Initiative Tracker with pre-made characters may have implications for desired behaviour when a character is selected within the view. Currently such a selection is interpreted as a desire to edit the character; this could potentially be modified to include a dialogue asking if the user wishes to edit the character, with (on confirmation) a change of view to the 'Characters' view (with appropriate character selected).

Alternatively, selecting a character on the Initiative Tracker view (and similar views) could open a dialogue with a selection of options: one being 'edit character' (behaving as described in the previous paragraph) and another being 'edit initiative', which would help with issue #3 (manual input of initiative rolls).

**Comment by tsiemens** [comment]
Sounds like a good idea. You can work on this.

**Comment by tsiemens** [comment]
This is now dependent on #29 being completed.
