### ISSUE TITLE
Initiative Tracker 'Cycle' Button

### ISSUE THREAD

**Issue by samcorcoran** [tsiemens/pathfinder-toolkit#19]
Character ordering on the initiative tracker is fixed after rolling occurs, but it would be useful to have a button which 'cycles' the list, placing the top entry at the bottom while making no other changes.

During play, at the beginning of an encounter, the character with the highest initiative will have the first turn. This notion of a character being the 'active' character (as they are the one for whom it is the 'current turn') continues down through the initiative order, before repeating from the beginning. Currently players would have to keep track whose turn it is, externally to the app.

The addition of a 'Next Turn' button (some other label phrasing may be preferable), which removes the first character from its datastructure and re-inserts it in the last position, would provide the desired effect.

However, characters involved are currently stored in a PTParty object, m_party. It seems like it would abuse the model to be 'removing' characters from a party (even if they are re-inserted). It may be preferable for a party imported into the 'Initiative Tracker' to be placed into a separate list used for tracking characters involved in the encounter. This list would be sorted following the rolling of initiative, and removal and re-insertion (at list's end) of the currently-first character would accommodate the cycling.

Additionally, tracking involved characters in a list that is separate to a PTParty object would pave the way for the importing of multiple parties (and individual standalone characters) into the 'Initiative Tracker', which would also be a very nice feature to see (albeit a separate issue to this one).

**Comment by tsiemens** [comment]
Sounds like a good idea. Our current data model will not support order preservation though. See my comment in #20.
