### ISSUE TITLE
Added Party members do not immediately appear

### ISSUE THREAD

**Issue by samcorcoran** [tsiemens/pathfinder-toolkit#34]
When creating a new party the user supplies a name, then touches the "Add characters" icon (face with a plus) and can select one or more characters to include, then press the tick button to add them.

Currently the newly added characters do not appear immediately. The list continues to show whatever characters (or no characters) were previously in the party. 

The added characters can be made to appear by switching to a different screen in the app (e.g. switching to the encounters page) and then back again. This suggests that the problem is that the view is not refreshing/redrawing the list after characters are added.

**Comment by tsiemens** [comment]
Fixed
