### ISSUE TITLE
Party member removal displays incorrect number of characters to be removed

### ISSUE THREAD

**Issue by samcorcoran** [tsiemens/pathfinder-toolkit#35]
Clicking and holding on a character in a party (in the Party Manager view) allows one or more characters to be selected, and the trash can icon can be clicked to remove the selected (highlighted) characters. 

Currently, if there are more party members than the selection (e.g. 4 members in total, with 2 selected for deletion) then the message displayed after clicking the trash can states that 4 characters will be removed. The number it shows here should be the number selected, rather than the full number available.

If you proceed with the removal then the correct characters are removed, so this bug must only be a problem with which number is displayed in the message.

**Comment by tsiemens** [comment]
Fixed. This also fixes the same issue in the encounter view.
