### ISSUE TITLE
Encounter re-ordering of a character on their turn can cause other characters to miss turns

### ISSUE THREAD

**Issue by samcorcoran** [tsiemens/pathfinder-toolkit#36]
If one character in an encounter of five others is dragged to a new position in the turn other (e.g. player elected to delay their turn until then) then the 'current turn' indicator moves with them. Pressing 'Next' Turn' after the move results in the characters inbetween the original and new position to be skipped - 'current turn' passes to the next player in the list from the new position.

To remedy this, when the user drags a character (whose turn it currently is)) to a new position then on release the turn marker should be incremented _before_ the change-of-order is put into effect.

For dragging of characters out-of-turn, no such incrementing of turn order should occur. Strictly speaking you shouldn't need to re-order any character other than the one whose turn it is (as it is a decision based event), but users will probably like the flexibility, just in case they need to tweak things.

**Comment by tsiemens** [comment]
Thanks for pointing this out. I was not really aware of the actual use case of re-ordering while implementing it.

**Comment by tsiemens** [comment]
Fixed.
