### ISSUE TITLE
New icon for Party Membership 'Create Character' button

### ISSUE THREAD

**Issue by samcorcoran** [tsiemens/pathfinder-toolkit#39]
This button uses the face with a plus icon, however in 'Party Manager' this same icon is used for adding an existing character. One of these needs a new icon! Perhaps they could be variations of the same image, such as a hollow, dotted outline of the face/person for when you are creating a new character (therefore suggesting that the character doesn't have substance yet), and the solid one for when you are choosing an existing character. In both cases, the plus symbol will imply they will be added to the party.

**Comment by tsiemens** [comment]
Fixed. Created icon like add character, but uses dotted lines.
