### ISSUE TITLE
Party Manager needs member removal icon that isn't a trash can

### ISSUE THREAD

**Issue by samcorcoran** [tsiemens/pathfinder-toolkit#42]
Currently the 'trash can' icon is used, but this is synonymous with deletion. Users might worry that their action will delete the character, rather than just remove them from the party. Perhaps a different icon would be better?

**Comment by tsiemens** [comment]
Will create android styled analog to this. http://icons.iconarchive.com/icons/fasticon/fast-icon-users/128/remove-user-icon.png

**Comment by tsiemens** [comment]
Fixed. icon is similar to add character, except the + is an X
